<#
.SYNOPSIS
    Generates ClangSharpConfig.generated.rsp by combining the base ClangSharpConfig.rsp
    with auto-generated --with-manual-import entries for every NVAPI function in
    nvapi_interface.h.

.DESCRIPTION
    NVAPI functions are not exported by nvapi64.dll as named symbols.  They must
    be resolved at runtime via NvAPI_QueryInterface.  ClangSharp's --with-manual-import
    option causes it to emit  delegate* unmanaged[Cdecl]<...>  function-pointer
    fields instead of [DllImport] methods.

    Because --with-manual-import does not support prefix wildcards we list every
    function individually.  This script reads the function names from
    nvapi_interface.h (the same source used by generate_nvapi_interface_table.ps1)
    and appends the matching RSP entries to the base config.

.NOTES
    Called automatically by the GenerateClangSharpConfig MSBuild target defined
    in NVAPIWrapper.csproj.
#>
param(
    [string]$HeaderPath     = (Join-Path $PSScriptRoot "nvapi\nvapi_interface.h"),
    [string]$BaseRspPath    = (Join-Path $PSScriptRoot "NVAPIWrapper\ClangSharpConfig.rsp"),
    [string]$OutputRspPath  = (Join-Path $PSScriptRoot "NVAPIWrapper\ClangSharpConfig.generated.rsp")
)

if (-not (Test-Path $HeaderPath)) {
    throw "NVAPI interface header not found: $HeaderPath"
}
if (-not (Test-Path $BaseRspPath)) {
    throw "Base ClangSharp RSP not found: $BaseRspPath"
}

# ── Parse function names from nvapi_interface.h ──────────────────────────────
$lines   = Get-Content -Path $HeaderPath
$inTable = $false
$funcNames = New-Object System.Collections.Generic.List[string]

foreach ($line in $lines) {
    if (-not $inTable) {
        if ($line -match 'nvapi_interface_table\[\]\s*=') {
            $inTable = $true
        }
        continue
    }
    if ($line -match '^\s*\};') {
        break
    }
    if ($line -match '\{\s*"([^"]+)"\s*,\s*0x[0-9a-fA-F]+\s*\}') {
        $funcNames.Add($matches[1]) | Out-Null
    }
}

if ($funcNames.Count -eq 0) {
    throw "No function entries found in nvapi_interface_table in $HeaderPath"
}

# ── Build the generated RSP ──────────────────────────────────────────────────
$output = New-Object System.Collections.Generic.List[string]

# Copy the entire base RSP
$output.Add("# <auto-generated>")
$output.Add("# Generated by generate_clangsharp_config.ps1.")
$output.Add("# DO NOT EDIT - changes will be overwritten. Edit ClangSharpConfig.rsp instead.")
$output.Add("# </auto-generated>")
$output.Add("")

$baseContent = Get-Content -Path $BaseRspPath -Raw
$output.Add($baseContent)

$output.Add("")
$count = $funcNames.Count
$output.Add("# --- AUTO-GENERATED MANUAL IMPORTS ($count functions) ---")
$output.Add("# Tells ClangSharp to emit delegate* function-pointer fields instead of")
$output.Add("# [DllImport] methods, since nvapi64.dll only exports NvAPI_QueryInterface.")
$output.Add("")

# Map every manual-import function into the NVAPI class individually,
# since --with-class only supports per-name or per-name prefix matching.
foreach ($name in $funcNames) {
    $output.Add("--with-manual-import")
    $output.Add($name)
    $output.Add("--with-class")
    $output.Add("$name=NVAPI")
}

# Write with UTF-8 no BOM (consistent with ClangSharp expectations)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputRspPath, ($output -join "`n"), $utf8NoBom)

Write-Host "Generated $OutputRspPath with $($funcNames.Count) manual-import entries."
