### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  commentId: T:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  id: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  - NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  langs:
  - csharp
  - vb
  name: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
    content.vb: Public Enum EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF = 0
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A = 1
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B = 2
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C = 3
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 18
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D = 4
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 21
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest = 16777215
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 24
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES = 6
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  parent: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  langs:
  - csharp
  - vb
  name: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
      branch: develop
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.cs
    startLine: 27
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  commentId: T:NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.html
  name: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  nameWithType: EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
  fullName: NVAPIWrapper.EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
