namespace NVAPIWrapper
{
    /// <include file='_NV_D3D12_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_D3D12_WORKSTATION_FEATURE_TYPE"]/*' />
    public enum _NV_D3D12_WORKSTATION_FEATURE_TYPE
    {
        /// <include file='_NV_D3D12_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_D3D12_WORKSTATION_FEATURE_TYPE.NV_D3D12_WORKSTATION_FEATURE_TYPE_PRESENT_BARRIER"]/*' />
        NV_D3D12_WORKSTATION_FEATURE_TYPE_PRESENT_BARRIER = 1,

        /// <include file='_NV_D3D12_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_D3D12_WORKSTATION_FEATURE_TYPE.NV_D3D12_WORKSTATION_FEATURE_TYPE_RDMA_BAR1_SUPPORT"]/*' />
        NV_D3D12_WORKSTATION_FEATURE_TYPE_RDMA_BAR1_SUPPORT = 2,
    }
}
