namespace NVAPIWrapper
{
    /// <include file='_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.xml' path='doc/member[@name="_NV_DISPLAYCONFIG_SPANNING_ORIENTATION"]/*' />
    public enum _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
    {
        /// <include file='_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.xml' path='doc/member[@name="_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE"]/*' />
        NV_DISPLAYCONFIG_SPAN_NONE = 0,

        /// <include file='_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.xml' path='doc/member[@name="_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL"]/*' />
        NV_DISPLAYCONFIG_SPAN_HORIZONTAL = 1,

        /// <include file='_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.xml' path='doc/member[@name="_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL"]/*' />
        NV_DISPLAYCONFIG_SPAN_VERTICAL = 2,
    }
}
