namespace NVAPIWrapper
{
    /// <include file='_NV_GPU_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_GPU_WORKSTATION_FEATURE_TYPE"]/*' />
    public enum _NV_GPU_WORKSTATION_FEATURE_TYPE
    {
        /// <include file='_NV_GPU_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_GPU_WORKSTATION_FEATURE_TYPE.NV_GPU_WORKSTATION_FEATURE_TYPE_NVIDIA_RTX_VR_READY"]/*' />
        NV_GPU_WORKSTATION_FEATURE_TYPE_NVIDIA_RTX_VR_READY = 1,

        /// <include file='_NV_GPU_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_GPU_WORKSTATION_FEATURE_TYPE.NV_GPU_WORKSTATION_FEATURE_TYPE_QUADRO_VR_READY"]/*' />
        NV_GPU_WORKSTATION_FEATURE_TYPE_QUADRO_VR_READY = NV_GPU_WORKSTATION_FEATURE_TYPE_NVIDIA_RTX_VR_READY,

        /// <include file='_NV_GPU_WORKSTATION_FEATURE_TYPE.xml' path='doc/member[@name="_NV_GPU_WORKSTATION_FEATURE_TYPE.NV_GPU_WORKSTATION_FEATURE_TYPE_PROVIZ"]/*' />
        NV_GPU_WORKSTATION_FEATURE_TYPE_PROVIZ = 2,
    }
}
