namespace NVAPIWrapper
{
    /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID"]/*' />
    public enum _NV_GPU_ARCH_IMPLEMENTATION_ID
    {
        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_T20"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_T20 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_T30"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_T30 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_T35"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_T35 = 0x00000005,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_T40"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_T40 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_T124"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_T124 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV40"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV40 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV41"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV41 = 0x00000001,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV42"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV42 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV43"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV43 = 0x00000003,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV44"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV44 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV44A"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV44A = 0x0000000A,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV46"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV46 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV47"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV47 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV49"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV49 = 0x00000009,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV4B"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV4B = 0x0000000B,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV4C"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV4C = 0x0000000C,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV4E"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV4E = 0x0000000E,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV50"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV50 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV63"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV63 = 0x00000003,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_NV67"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_NV67 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G84"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G84 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G86"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G86 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G92"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G92 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G94"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G94 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G96"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G96 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_G98"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_G98 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT200"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT200 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT212"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT212 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT214"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT214 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT215"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT215 = 0x00000003,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT216"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT216 = 0x00000005,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT218"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT218 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_MCP77"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_MCP77 = 0x0000000A,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT21C"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT21C = 0x0000000B,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_MCP79"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_MCP79 = 0x0000000C,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GT21A"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GT21A = 0x0000000D,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_MCP89"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_MCP89 = 0x0000000F,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF100"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF100 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF106"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF106 = 0x00000003,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF108"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF108 = 0x00000001,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF110"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF110 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF116"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF116 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF117"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF117 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF118"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF118 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GF119"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GF119 = 0x00000009,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK106"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK106 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK107"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK107 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK20A"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK20A = 0x0000000A,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK110"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK110 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GK208"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GK208 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GM204"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GM204 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GM206"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GM206 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP100"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP100 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP000"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP000 = 0x00000001,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP102"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP102 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP106"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP106 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP107"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP107 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GP108"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GP108 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GV100"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GV100 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GV10B"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GV10B = 0x0000000B,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU100"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU100 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU102"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU102 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU106"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU106 = 0x00000006,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU116"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU116 = 0x00000008,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU117"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU117 = 0x00000007,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_TU000"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_TU000 = 0x00000001,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GA100"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GA100 = 0x00000000,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GA102"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GA102 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GA104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GA104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_AD102"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_AD102 = 0x00000002,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_AD103"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_AD103 = 0x00000003,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_AD104"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_AD104 = 0x00000004,

        /// <include file='_NV_GPU_ARCH_IMPLEMENTATION_ID.xml' path='doc/member[@name="_NV_GPU_ARCH_IMPLEMENTATION_ID.NV_GPU_ARCH_IMPLEMENTATION_GB202"]/*' />
        NV_GPU_ARCH_IMPLEMENTATION_GB202 = 0x00000002,
    }
}
