namespace NVAPIWrapper
{
    /// <include file='_NVAPI_STEREO_INIT_ACTIVATION_FLAGS.xml' path='doc/member[@name="_NVAPI_STEREO_INIT_ACTIVATION_FLAGS"]/*' />
    public enum _NVAPI_STEREO_INIT_ACTIVATION_FLAGS
    {
        /// <include file='_NVAPI_STEREO_INIT_ACTIVATION_FLAGS.xml' path='doc/member[@name="_NVAPI_STEREO_INIT_ACTIVATION_FLAGS.NVAPI_STEREO_INIT_ACTIVATION_IMMEDIATE"]/*' />
        NVAPI_STEREO_INIT_ACTIVATION_IMMEDIATE = 0X00,

        /// <include file='_NVAPI_STEREO_INIT_ACTIVATION_FLAGS.xml' path='doc/member[@name="_NVAPI_STEREO_INIT_ACTIVATION_FLAGS.NVAPI_STEREO_INIT_ACTIVATION_DELAYED"]/*' />
        NVAPI_STEREO_INIT_ACTIVATION_DELAYED = 0x01,
    }
}
