namespace NVAPIWrapper
{
    /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE"]/*' />
    public enum _NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE
    {
        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_EBRIDGE"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_EBRIDGE,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_NPU"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_NPU,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_GPU"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_GPU,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_SWITCH"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_SWITCH,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_TEGRA"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_TEGRA,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_NONE"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE_NONE,

        /// <include file='_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.xml' path='doc/member[@name="_NVAPI_NVLINK_DEVICE_INFO_DEVICE_TYPE.NVAPI_NVLINK_DEVICE_INFO_DEVICE_UUID_INVALID"]/*' />
        NVAPI_NVLINK_DEVICE_INFO_DEVICE_UUID_INVALID,
    }
}
