namespace NVAPIWrapper
{
    /// <include file='_NVAPI_STEREO_SURFACECREATEMODE.xml' path='doc/member[@name="_NVAPI_STEREO_SURFACECREATEMODE"]/*' />
    public enum _NVAPI_STEREO_SURFACECREATEMODE
    {
        /// <include file='_NVAPI_STEREO_SURFACECREATEMODE.xml' path='doc/member[@name="_NVAPI_STEREO_SURFACECREATEMODE.NVAPI_STEREO_SURFACECREATEMODE_AUTO"]/*' />
        NVAPI_STEREO_SURFACECREATEMODE_AUTO,

        /// <include file='_NVAPI_STEREO_SURFACECREATEMODE.xml' path='doc/member[@name="_NVAPI_STEREO_SURFACECREATEMODE.NVAPI_STEREO_SURFACECREATEMODE_FORCESTEREO"]/*' />
        NVAPI_STEREO_SURFACECREATEMODE_FORCESTEREO,

        /// <include file='_NVAPI_STEREO_SURFACECREATEMODE.xml' path='doc/member[@name="_NVAPI_STEREO_SURFACECREATEMODE.NVAPI_STEREO_SURFACECREATEMODE_FORCEMONO"]/*' />
        NVAPI_STEREO_SURFACECREATEMODE_FORCEMONO,
    }
}
