namespace NVAPIWrapper
{
    /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR"]/*' />
    public enum _NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR
    {
        /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_NONE"]/*' />
        NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_NONE = 0,

        /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_PRIMARY"]/*' />
        NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_PRIMARY = 1,

        /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_SECONDARY"]/*' />
        NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_SECONDARY = 2,

        /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_TERTIARY"]/*' />
        NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_TERTIARY = 3,

        /// <include file='_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.xml' path='doc/member[@name="_NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR.NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_QUARTERNARY"]/*' />
        NVAPI_GSYNC_GPU_TOPOLOGY_CONNECTOR_QUARTERNARY = 4,
    }
}
