namespace NVAPIWrapper
{
    /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE"]/*' />
    public enum _NVAPI_NVLINK_STATUS_LINK_STATE
    {
        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_UNKNOWN"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_UNKNOWN,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_INIT"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_INIT,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_HWCFG"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_HWCFG,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_SWCFG"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_SWCFG,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_ACTIVE"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_ACTIVE,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_FAULT"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_FAULT,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY_AC"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY_AC,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY_AX"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_RECOVERY_AX,

        /// <include file='_NVAPI_NVLINK_STATUS_LINK_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_LINK_STATE.NVAPI_NVLINK_STATUS_LINK_STATE_INVALID"]/*' />
        NVAPI_NVLINK_STATUS_LINK_STATE_INVALID = unchecked((int)(0xFFFFFFFF)),
    }
}
