namespace NVAPIWrapper
{
    /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE"]/*' />
    public enum _NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE
    {
        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_UNKNOWN"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_UNKNOWN,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_HIGH_SPEED_1"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_HIGH_SPEED_1,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_LOW_POWER"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_LOW_POWER,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_TRAINING"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_TRAINING,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_SAFE_MODE"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_SAFE_MODE,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_OFF"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_OFF,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_TEST"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_TEST,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_FAULT"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_FAULT,

        /// <include file='_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.xml' path='doc/member[@name="_NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE.NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_INVALID"]/*' />
        NVAPI_NVLINK_STATUS_SUBLINK_RX_STATE_INVALID = 0xFF,
    }
}
