namespace NVAPIWrapper
{
    /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING"]/*' />
    public enum _NVVIOCOMPONENTSAMPLING
    {
        /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING.NVVIOCOMPONENTSAMPLING_UNKNOWN"]/*' />
        NVVIOCOMPONENTSAMPLING_UNKNOWN,

        /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING.NVVIOCOMPONENTSAMPLING_4444"]/*' />
        NVVIOCOMPONENTSAMPLING_4444,

        /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING.NVVIOCOMPONENTSAMPLING_4224"]/*' />
        NVVIOCOMPONENTSAMPLING_4224,

        /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING.NVVIOCOMPONENTSAMPLING_444"]/*' />
        NVVIOCOMPONENTSAMPLING_444,

        /// <include file='_NVVIOCOMPONENTSAMPLING.xml' path='doc/member[@name="_NVVIOCOMPONENTSAMPLING.NVVIOCOMPONENTSAMPLING_422"]/*' />
        NVVIOCOMPONENTSAMPLING_422,
    }
}
