namespace NVAPIWrapper
{
    /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT"]/*' />
    public enum _NVVIODATAFORMAT
    {
        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_UNKNOWN"]/*' />
        NVVIODATAFORMAT_UNKNOWN = -1,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8_TO_YCRCB444"]/*' />
        NVVIODATAFORMAT_R8G8B8_TO_YCRCB444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8A8_TO_YCRCBA4444"]/*' />
        NVVIODATAFORMAT_R8G8B8A8_TO_YCRCBA4444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8Z10_TO_YCRCBZ4444"]/*' />
        NVVIODATAFORMAT_R8G8B8Z10_TO_YCRCBZ4444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8_TO_YCRCB422"]/*' />
        NVVIODATAFORMAT_R8G8B8_TO_YCRCB422,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8A8_TO_YCRCBA4224"]/*' />
        NVVIODATAFORMAT_R8G8B8A8_TO_YCRCBA4224,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R8G8B8Z10_TO_YCRCBZ4224"]/*' />
        NVVIODATAFORMAT_R8G8B8Z10_TO_YCRCBZ4224,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X8X8X8_444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X8X8X8_444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X8X8X8A8_4444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X8X8X8A8_4444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X8X8X8Z10_4444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X8X8X8Z10_4444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X10X10X10_444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X10X10X10_444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X10X8X8_444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X10X8X8_444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X10X8X8A10_4444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X10X8X8A10_4444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X10X8X8Z10_4444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X10X8X8Z10_4444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_DUAL_R8G8B8_TO_DUAL_YCRCB422"]/*' />
        NVVIODATAFORMAT_DUAL_R8G8B8_TO_DUAL_YCRCB422,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_DUAL_X8X8X8_TO_DUAL_422_PASSTHRU"]/*' />
        NVVIODATAFORMAT_DUAL_X8X8X8_TO_DUAL_422_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R10G10B10_TO_YCRCB422"]/*' />
        NVVIODATAFORMAT_R10G10B10_TO_YCRCB422,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R10G10B10_TO_YCRCB444"]/*' />
        NVVIODATAFORMAT_R10G10B10_TO_YCRCB444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X12X12X12_444_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X12X12X12_444_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_X12X12X12_422_PASSTHRU"]/*' />
        NVVIODATAFORMAT_X12X12X12_422_PASSTHRU,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_Y10CR10CB10_TO_YCRCB422"]/*' />
        NVVIODATAFORMAT_Y10CR10CB10_TO_YCRCB422,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_Y8CR8CB8_TO_YCRCB422"]/*' />
        NVVIODATAFORMAT_Y8CR8CB8_TO_YCRCB422,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_Y10CR8CB8A10_TO_YCRCBA4224"]/*' />
        NVVIODATAFORMAT_Y10CR8CB8A10_TO_YCRCBA4224,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R10G10B10_TO_RGB444"]/*' />
        NVVIODATAFORMAT_R10G10B10_TO_RGB444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R12G12B12_TO_YCRCB444"]/*' />
        NVVIODATAFORMAT_R12G12B12_TO_YCRCB444,

        /// <include file='_NVVIODATAFORMAT.xml' path='doc/member[@name="_NVVIODATAFORMAT.NVVIODATAFORMAT_R12G12B12_TO_YCRCB422"]/*' />
        NVVIODATAFORMAT_R12G12B12_TO_YCRCB422,
    }
}
