namespace NVAPIWrapper
{
    /// <include file='_NVVIOANCPARITYCOMPUTATION.xml' path='doc/member[@name="_NVVIOANCPARITYCOMPUTATION"]/*' />
    public enum _NVVIOANCPARITYCOMPUTATION
    {
        /// <include file='_NVVIOANCPARITYCOMPUTATION.xml' path='doc/member[@name="_NVVIOANCPARITYCOMPUTATION.NVVIOANCPARITYCOMPUTATION_AUTO"]/*' />
        NVVIOANCPARITYCOMPUTATION_AUTO,

        /// <include file='_NVVIOANCPARITYCOMPUTATION.xml' path='doc/member[@name="_NVVIOANCPARITYCOMPUTATION.NVVIOANCPARITYCOMPUTATION_ON"]/*' />
        NVVIOANCPARITYCOMPUTATION_ON,

        /// <include file='_NVVIOANCPARITYCOMPUTATION.xml' path='doc/member[@name="_NVVIOANCPARITYCOMPUTATION.NVVIOANCPARITYCOMPUTATION_OFF"]/*' />
        NVVIOANCPARITYCOMPUTATION_OFF,
    }
}
