namespace NVAPIWrapper
{
    /// <include file='EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.xml' path='doc/member[@name="EValues_PS_TEXFILTER_BILINEAR_IN_ANISO"]/*' />
    public enum EValues_PS_TEXFILTER_BILINEAR_IN_ANISO
    {
        /// <include file='EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.xml' path='doc/member[@name="EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.PS_TEXFILTER_BILINEAR_IN_ANISO_OFF"]/*' />
        PS_TEXFILTER_BILINEAR_IN_ANISO_OFF = 0x00000000,

        /// <include file='EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.xml' path='doc/member[@name="EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.PS_TEXFILTER_BILINEAR_IN_ANISO_ON"]/*' />
        PS_TEXFILTER_BILINEAR_IN_ANISO_ON = 0x00000001,

        /// <include file='EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.xml' path='doc/member[@name="EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.PS_TEXFILTER_BILINEAR_IN_ANISO_NUM_VALUES"]/*' />
        PS_TEXFILTER_BILINEAR_IN_ANISO_NUM_VALUES = 2,

        /// <include file='EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.xml' path='doc/member[@name="EValues_PS_TEXFILTER_BILINEAR_IN_ANISO.PS_TEXFILTER_BILINEAR_IN_ANISO_DEFAULT"]/*' />
        PS_TEXFILTER_BILINEAR_IN_ANISO_DEFAULT = PS_TEXFILTER_BILINEAR_IN_ANISO_OFF,
    }
}
