namespace NVAPIWrapper
{
    /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS"]/*' />
    [NativeTypeName("int")]
    public enum EValues_SHIM_RENDERING_OPTIONS : uint
    {
        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DEFAULT_RENDERING_MODE"]/*' />
        SHIM_RENDERING_OPTIONS_DEFAULT_RENDERING_MODE = 0x00000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_ASYNC_PRESENT"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_ASYNC_PRESENT = 0x00000001U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_EHSHELL_DETECT"]/*' />
        SHIM_RENDERING_OPTIONS_EHSHELL_DETECT = 0x00000002U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_FLASHPLAYER_HOST_DETECT"]/*' />
        SHIM_RENDERING_OPTIONS_FLASHPLAYER_HOST_DETECT = 0x00000004U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_VIDEO_DRM_APP_DETECT"]/*' />
        SHIM_RENDERING_OPTIONS_VIDEO_DRM_APP_DETECT = 0x00000008U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_IGNORE_OVERRIDES"]/*' />
        SHIM_RENDERING_OPTIONS_IGNORE_OVERRIDES = 0x00000010U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_RESERVED1"]/*' />
        SHIM_RENDERING_OPTIONS_RESERVED1 = 0x00000020U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ENABLE_DWM_ASYNC_PRESENT"]/*' />
        SHIM_RENDERING_OPTIONS_ENABLE_DWM_ASYNC_PRESENT = 0x00000040U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_RESERVED2"]/*' />
        SHIM_RENDERING_OPTIONS_RESERVED2 = 0x00000080U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ALLOW_INHERITANCE"]/*' />
        SHIM_RENDERING_OPTIONS_ALLOW_INHERITANCE = 0x00000100U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_WRAPPERS"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_WRAPPERS = 0x00000200U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_DXGI_WRAPPERS"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_DXGI_WRAPPERS = 0x00000400U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_PRUNE_UNSUPPORTED_FORMATS"]/*' />
        SHIM_RENDERING_OPTIONS_PRUNE_UNSUPPORTED_FORMATS = 0x00000800U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ENABLE_ALPHA_FORMAT"]/*' />
        SHIM_RENDERING_OPTIONS_ENABLE_ALPHA_FORMAT = 0x00001000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_IGPU_TRANSCODING"]/*' />
        SHIM_RENDERING_OPTIONS_IGPU_TRANSCODING = 0x00002000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_CUDA"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_CUDA = 0x00004000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ALLOW_CP_CAPS_FOR_VIDEO"]/*' />
        SHIM_RENDERING_OPTIONS_ALLOW_CP_CAPS_FOR_VIDEO = 0x00008000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_IGPU_TRANSCODING_FWD_OPTIMUS"]/*' />
        SHIM_RENDERING_OPTIONS_IGPU_TRANSCODING_FWD_OPTIMUS = 0x00010000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_DURING_SECURE_BOOT"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_DURING_SECURE_BOOT = 0x00020000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_INVERT_FOR_QUADRO"]/*' />
        SHIM_RENDERING_OPTIONS_INVERT_FOR_QUADRO = 0x00040000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_INVERT_FOR_MSHYBRID"]/*' />
        SHIM_RENDERING_OPTIONS_INVERT_FOR_MSHYBRID = 0x00080000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_REGISTER_PROCESS_ENABLE_GOLD"]/*' />
        SHIM_RENDERING_OPTIONS_REGISTER_PROCESS_ENABLE_GOLD = 0x00100000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_HANDLE_WINDOWED_MODE_PERF_OPT"]/*' />
        SHIM_RENDERING_OPTIONS_HANDLE_WINDOWED_MODE_PERF_OPT = 0x00200000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_HANDLE_WIN7_ASYNC_RUNTIME_BUG"]/*' />
        SHIM_RENDERING_OPTIONS_HANDLE_WIN7_ASYNC_RUNTIME_BUG = 0x00400000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_EXPLICIT_ADAPTER_OPTED_BY_APP"]/*' />
        SHIM_RENDERING_OPTIONS_EXPLICIT_ADAPTER_OPTED_BY_APP = 0x00800000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ALLOW_DYNAMIC_DISPLAY_MUX_SWITCH"]/*' />
        SHIM_RENDERING_OPTIONS_ALLOW_DYNAMIC_DISPLAY_MUX_SWITCH = 0x01000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISALLOW_DYNAMIC_DISPLAY_MUX_SWITCH"]/*' />
        SHIM_RENDERING_OPTIONS_DISALLOW_DYNAMIC_DISPLAY_MUX_SWITCH = 0x02000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISABLE_TURING_POWER_POLICY"]/*' />
        SHIM_RENDERING_OPTIONS_DISABLE_TURING_POWER_POLICY = 0x04000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_ALLOW_DYNAMIC_DISPLAY_MUX_SWITCH_MDM"]/*' />
        SHIM_RENDERING_OPTIONS_ALLOW_DYNAMIC_DISPLAY_MUX_SWITCH_MDM = 0x08000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DISALLOW_DYNAMIC_DISPLAY_MUX_SWITCH_MDM"]/*' />
        SHIM_RENDERING_OPTIONS_DISALLOW_DYNAMIC_DISPLAY_MUX_SWITCH_MDM = 0x10000000U,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_NUM_VALUES"]/*' />
        SHIM_RENDERING_OPTIONS_NUM_VALUES = 30,

        /// <include file='EValues_SHIM_RENDERING_OPTIONS.xml' path='doc/member[@name="EValues_SHIM_RENDERING_OPTIONS.SHIM_RENDERING_OPTIONS_DEFAULT"]/*' />
        SHIM_RENDERING_OPTIONS_DEFAULT = 0x00000000U,
    }
}
