namespace NVAPIWrapper
{
    /// <include file='EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.xml' path='doc/member[@name="EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE"]/*' />
    public enum EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE
    {
        /// <include file='EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.xml' path='doc/member[@name="EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.PS_TEXFILTER_DISABLE_TRILIN_SLOPE_OFF"]/*' />
        PS_TEXFILTER_DISABLE_TRILIN_SLOPE_OFF = 0x00000000,

        /// <include file='EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.xml' path='doc/member[@name="EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.PS_TEXFILTER_DISABLE_TRILIN_SLOPE_ON"]/*' />
        PS_TEXFILTER_DISABLE_TRILIN_SLOPE_ON = 0x00000001,

        /// <include file='EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.xml' path='doc/member[@name="EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.PS_TEXFILTER_DISABLE_TRILIN_SLOPE_NUM_VALUES"]/*' />
        PS_TEXFILTER_DISABLE_TRILIN_SLOPE_NUM_VALUES = 2,

        /// <include file='EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.xml' path='doc/member[@name="EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE.PS_TEXFILTER_DISABLE_TRILIN_SLOPE_DEFAULT"]/*' />
        PS_TEXFILTER_DISABLE_TRILIN_SLOPE_DEFAULT = PS_TEXFILTER_DISABLE_TRILIN_SLOPE_OFF,
    }
}
