namespace NVAPIWrapper
{
    /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD"]/*' />
    public enum EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD
    {
        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_DISABLE"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_DISABLE = 0,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_CRITICAL"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_CRITICAL = 1,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_WARNING"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_WARNING = 2,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_INFORMATION"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_INFORMATION = 3,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_ALL"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_ALL = 4,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_NUM_VALUES"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_NUM_VALUES = 5,

        /// <include file='EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.xml' path='doc/member[@name="EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD.OGL_EVENT_LOG_SEVERITY_THRESHOLD_DEFAULT"]/*' />
        OGL_EVENT_LOG_SEVERITY_THRESHOLD_DEFAULT = OGL_EVENT_LOG_SEVERITY_THRESHOLD_ALL,
    }
}
