namespace NVAPIWrapper
{
    /// <include file='EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.xml' path='doc/member[@name="EValues_QUALITY_ENHANCEMENT_SUBSTITUTION"]/*' />
    public enum EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
    {
        /// <include file='EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.xml' path='doc/member[@name="EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION"]/*' />
        QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION = 0x00000000,

        /// <include file='EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.xml' path='doc/member[@name="EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY"]/*' />
        QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY = 0x00000001,

        /// <include file='EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.xml' path='doc/member[@name="EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES"]/*' />
        QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES = 2,

        /// <include file='EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.xml' path='doc/member[@name="EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT"]/*' />
        QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT = QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION,
    }
}
