namespace NVAPIWrapper
{
    /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT"]/*' />
    public enum EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
    {
        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED = 0,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS = 9,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS = 15,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS = 30,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE = 60,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES = 120,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES = 6,

        /// <include file='EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.xml' path='doc/member[@name="EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT"]/*' />
        APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT = APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED,
    }
}
