namespace NVAPIWrapper
{
    /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10"]/*' />
    public enum EValues_SLI_PREDEFINED_GPU_COUNT_DX10
    {
        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_AUTOSELECT"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_AUTOSELECT = 0x00000000,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_ONE"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_ONE = 0x00000001,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_TWO"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_TWO = 0x00000002,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_THREE"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_THREE = 0x00000003,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_FOUR"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_FOUR = 0x00000004,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_NUM_VALUES"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_NUM_VALUES = 5,

        /// <include file='EValues_SLI_PREDEFINED_GPU_COUNT_DX10.xml' path='doc/member[@name="EValues_SLI_PREDEFINED_GPU_COUNT_DX10.SLI_PREDEFINED_GPU_COUNT_DX10_DEFAULT"]/*' />
        SLI_PREDEFINED_GPU_COUNT_DX10_DEFAULT = SLI_PREDEFINED_GPU_COUNT_DX10_AUTOSELECT,
    }
}
