namespace NVAPIWrapper
{
    /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX"]/*' />
    public enum EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX
    {
        /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_OFF"]/*' />
        NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_OFF = 0,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_MIN"]/*' />
        NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_MIN = 1,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_MAX"]/*' />
        NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_MAX = 16777215,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_NUM_VALUES"]/*' />
        NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_NUM_VALUES = 3,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX.NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_DEFAULT"]/*' />
        NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_DEFAULT = NGX_DLSSG_DYNAMIC_MULTI_FRAME_COUNT_MAX_OFF,
    }
}
