namespace NVAPIWrapper
{
    /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION"]/*' />
    public enum EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION
    {
        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF = 0,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A = 1,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B = 2,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C = 3,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D = 4,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest = 0x00ffffff,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES = 6,

        /// <include file='EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT"]/*' />
        NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT = NGX_DLSS_NR_OVERRIDE_RENDER_PRESET_SELECTION_OFF,
    }
}
