namespace NVAPIWrapper
{
    /// <include file='EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.xml' path='doc/member[@name="EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS"]/*' />
    public enum EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
    {
        /// <include file='EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.xml' path='doc/member[@name="EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE"]/*' />
        NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE = 0x0000,

        /// <include file='EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.xml' path='doc/member[@name="EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X"]/*' />
        NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X = 0x0001,

        /// <include file='EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.xml' path='doc/member[@name="EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES"]/*' />
        NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES = 2,

        /// <include file='EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.xml' path='doc/member[@name="EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT"]/*' />
        NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT = NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE,
    }
}
