namespace NVAPIWrapper
{
    /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN"]/*' />
    public enum EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN
    {
        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.OGL_DEFAULT_SWAP_INTERVAL_SIGN_POSITIVE"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_SIGN_POSITIVE = 0,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.OGL_DEFAULT_SWAP_INTERVAL_SIGN_NEGATIVE"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_SIGN_NEGATIVE = 1,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.OGL_DEFAULT_SWAP_INTERVAL_SIGN_NUM_VALUES"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_SIGN_NUM_VALUES = 2,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN.OGL_DEFAULT_SWAP_INTERVAL_SIGN_DEFAULT"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_SIGN_DEFAULT = OGL_DEFAULT_SWAP_INTERVAL_SIGN_POSITIVE,
    }
}
