namespace NVAPIWrapper
{
    /// <include file='EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.xml' path='doc/member[@name="EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE"]/*' />
    public enum EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE
    {
        /// <include file='EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.xml' path='doc/member[@name="EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_OFF"]/*' />
        SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_OFF = 0x00000000,

        /// <include file='EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.xml' path='doc/member[@name="EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_ON"]/*' />
        SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_ON = 0x00000001,

        /// <include file='EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.xml' path='doc/member[@name="EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_NUM_VALUES"]/*' />
        SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_NUM_VALUES = 2,

        /// <include file='EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.xml' path='doc/member[@name="EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE.SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_DEFAULT"]/*' />
        SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_DEFAULT = SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_OFF,
    }
}
