namespace NVAPIWrapper
{
    /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION"]/*' />
    public enum EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION
    {
        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_OFF"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_OFF = 0,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_A = 1,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_B = 2,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_C = 3,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_D = 4,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_E"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_E = 5,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_F"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_F = 6,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_G"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_G = 7,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_H"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_H = 8,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_I"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_I = 9,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_J"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_J = 10,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_K"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_K = 11,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_L"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_L = 12,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_M"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_M = 13,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_N"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_N = 14,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_O"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_O = 15,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_P"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_P = 16,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Q"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Q = 17,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_R"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_R = 18,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_S"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_S = 19,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_T"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_T = 20,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_U"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_U = 21,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_V"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_V = 22,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_W"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_W = 23,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_X"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_X = 24,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Y"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Y = 25,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Z"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Z = 26,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Default"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Default = 0x00fffffe,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_RENDER_PRESET_Latest = 0x00ffffff,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_NUM_VALUES = 29,

        /// <include file='EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.xml' path='doc/member[@name="EValues_NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION.NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT"]/*' />
        NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_DEFAULT = NGX_DLSS_FG_OVERRIDE_RENDER_PRESET_SELECTION_OFF,
    }
}
