namespace NVAPIWrapper
{
    /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL"]/*' />
    public enum EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
    {
        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES = 0,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES = 100,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES = 2,

        /// <include file='EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.xml' path='doc/member[@name="EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT"]/*' />
        OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT = 0U,
    }
}
