namespace NVAPIWrapper
{
    /// <include file='EValues_LATENCY_INDICATOR_AUTOALIGN.xml' path='doc/member[@name="EValues_LATENCY_INDICATOR_AUTOALIGN"]/*' />
    public enum EValues_LATENCY_INDICATOR_AUTOALIGN
    {
        /// <include file='EValues_LATENCY_INDICATOR_AUTOALIGN.xml' path='doc/member[@name="EValues_LATENCY_INDICATOR_AUTOALIGN.LATENCY_INDICATOR_AUTOALIGN_DISABLED"]/*' />
        LATENCY_INDICATOR_AUTOALIGN_DISABLED = 0x0,

        /// <include file='EValues_LATENCY_INDICATOR_AUTOALIGN.xml' path='doc/member[@name="EValues_LATENCY_INDICATOR_AUTOALIGN.LATENCY_INDICATOR_AUTOALIGN_ENABLED"]/*' />
        LATENCY_INDICATOR_AUTOALIGN_ENABLED = 0x1,

        /// <include file='EValues_LATENCY_INDICATOR_AUTOALIGN.xml' path='doc/member[@name="EValues_LATENCY_INDICATOR_AUTOALIGN.LATENCY_INDICATOR_AUTOALIGN_NUM_VALUES"]/*' />
        LATENCY_INDICATOR_AUTOALIGN_NUM_VALUES = 2,

        /// <include file='EValues_LATENCY_INDICATOR_AUTOALIGN.xml' path='doc/member[@name="EValues_LATENCY_INDICATOR_AUTOALIGN.LATENCY_INDICATOR_AUTOALIGN_DEFAULT"]/*' />
        LATENCY_INDICATOR_AUTOALIGN_DEFAULT = LATENCY_INDICATOR_AUTOALIGN_ENABLED,
    }
}
