namespace NVAPIWrapper
{
    /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE"]/*' />
    public enum EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE
    {
        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_DISABLED"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_DISABLED = 0,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_MIN"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_MIN = 0x00000001,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_MAX"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_MAX = 0x00FFFFFF,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_AUTO"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_AUTO = 0x01000000,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_NUM_VALUES"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_NUM_VALUES = 4,

        /// <include file='EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.xml' path='doc/member[@name="EValues_NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE.NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_DEFAULT"]/*' />
        NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_DEFAULT = NGX_DLSSG_DYNAMIC_TARGET_FRAME_RATE_DISABLED,
    }
}
