namespace NVAPIWrapper
{
    /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE"]/*' />
    public enum EValues_VRR_APP_OVERRIDE_REQUEST_STATE
    {
        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_ALLOW"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_ALLOW = 0,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_FORCE_OFF"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_FORCE_OFF = 1,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_DISALLOW"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_DISALLOW = 2,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_ULMB"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_ULMB = 3,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_FIXED_REFRESH"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_FIXED_REFRESH = 4,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_NUM_VALUES"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_NUM_VALUES = 5,

        /// <include file='EValues_VRR_APP_OVERRIDE_REQUEST_STATE.xml' path='doc/member[@name="EValues_VRR_APP_OVERRIDE_REQUEST_STATE.VRR_APP_OVERRIDE_REQUEST_STATE_DEFAULT"]/*' />
        VRR_APP_OVERRIDE_REQUEST_STATE_DEFAULT = VRR_APP_OVERRIDE_REQUEST_STATE_ALLOW,
    }
}
