namespace NVAPIWrapper
{
    /// <include file='NV_GPU_WARPING_VERTICE_FORMAT.xml' path='doc/member[@name="NV_GPU_WARPING_VERTICE_FORMAT"]/*' />
    public enum NV_GPU_WARPING_VERTICE_FORMAT
    {
        /// <include file='NV_GPU_WARPING_VERTICE_FORMAT.xml' path='doc/member[@name="NV_GPU_WARPING_VERTICE_FORMAT.NV_GPU_WARPING_VERTICE_FORMAT_TRIANGLESTRIP_XYUVRQ"]/*' />
        NV_GPU_WARPING_VERTICE_FORMAT_TRIANGLESTRIP_XYUVRQ = 0,

        /// <include file='NV_GPU_WARPING_VERTICE_FORMAT.xml' path='doc/member[@name="NV_GPU_WARPING_VERTICE_FORMAT.NV_GPU_WARPING_VERTICE_FORMAT_TRIANGLES_XYUVRQ"]/*' />
        NV_GPU_WARPING_VERTICE_FORMAT_TRIANGLES_XYUVRQ = 1,
    }
}
