namespace NVAPIWrapper
{
    /// <include file='NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE"]/*' />
    public enum NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE
    {
        /// <include file='NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_HALF_HALT"]/*' />
        NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_HALF_HALT = 0,

        /// <include file='NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_FULL_HALT"]/*' />
        NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_FULL_HALT,

        /// <include file='NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_FULL_REPEAT"]/*' />
        NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_FULL_REPEAT,

        /// <include file='NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_TYPE.NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_INVALID"]/*' />
        NV_GPU_CLIENT_ILLUM_PIECEWISE_LINEAR_CYCLE_INVALID = 0xFF,
    }
}
