namespace NVAPIWrapper
{
    /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE"]/*' />
    public enum NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE
    {
        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_SET_TO_DEFAULT"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_SET_TO_DEFAULT = 0,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BILINEAR"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BILINEAR = 0x100,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_TRIANGULAR"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_TRIANGULAR = 0x101,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_BELL_SHAPED"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_BELL_SHAPED = 0x102,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_BSPLINE"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_BSPLINE = 0x103,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_TRIANGULAR"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_TRIANGULAR = 0x104,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_BELL_SHAPED"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_BELL_SHAPED = 0x105,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_BSPLINE"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_WARPING_RESAMPLING_METHOD_BICUBIC_ADAPTIVE_BSPLINE = 0x106,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_NO_GAMMA"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_NO_GAMMA = 0x200,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_COLOR_GAMMA"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_COLOR_GAMMA = 0x201,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_COLOR_AND_OFFSET_GAMMA"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_VALUE_SCANOUT_INTENSITY_COLOR_AND_OFFSET_GAMMA = 0x202,
    }
}
