namespace NVAPIWrapper
{
    /// <include file='NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_DEVICE_TYPE"]/*' />
    public enum NV_GPU_CLIENT_ILLUM_DEVICE_TYPE
    {
        /// <include file='NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_INVALID"]/*' />
        NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_INVALID = 0,

        /// <include file='NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_MCUV10"]/*' />
        NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_MCUV10,

        /// <include file='NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_GPIO_PWM_RGBW_V10"]/*' />
        NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_GPIO_PWM_RGBW_V10,

        /// <include file='NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_DEVICE_TYPE.NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_GPIO_PWM_SINGLE_COLOR_V10"]/*' />
        NV_GPU_CLIENT_ILLUM_DEVICE_TYPE_GPIO_PWM_SINGLE_COLOR_V10,
    }
}
