namespace NVAPIWrapper
{
    /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE"]/*' />
    public enum NV_GPU_CLIENT_ILLUM_CTRL_MODE
    {
        /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE.NV_GPU_CLIENT_ILLUM_CTRL_MODE_MANUAL_RGB"]/*' />
        NV_GPU_CLIENT_ILLUM_CTRL_MODE_MANUAL_RGB = 0,

        /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE.NV_GPU_CLIENT_ILLUM_CTRL_MODE_PIECEWISE_LINEAR_RGB"]/*' />
        NV_GPU_CLIENT_ILLUM_CTRL_MODE_PIECEWISE_LINEAR_RGB,

        /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE.NV_GPU_CLIENT_ILLUM_CTRL_MODE_MANUAL"]/*' />
        NV_GPU_CLIENT_ILLUM_CTRL_MODE_MANUAL = 0,

        /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE.NV_GPU_CLIENT_ILLUM_CTRL_MODE_PIECEWISE_LINEAR"]/*' />
        NV_GPU_CLIENT_ILLUM_CTRL_MODE_PIECEWISE_LINEAR,

        /// <include file='NV_GPU_CLIENT_ILLUM_CTRL_MODE.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_CTRL_MODE.NV_GPU_CLIENT_ILLUM_CTRL_MODE_INVALID"]/*' />
        NV_GPU_CLIENT_ILLUM_CTRL_MODE_INVALID = 0xFF,
    }
}
