namespace NVAPIWrapper
{
    /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION"]/*' />
    public enum NV_GPU_CLIENT_ILLUM_ZONE_LOCATION
    {
        /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_TOP_0"]/*' />
        NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_TOP_0 = 0x00,

        /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_FRONT_0"]/*' />
        NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_FRONT_0 = 0x08,

        /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_BACK_0"]/*' />
        NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_GPU_BACK_0 = 0x0C,

        /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_SLI_TOP_0"]/*' />
        NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_SLI_TOP_0 = 0x20,

        /// <include file='NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.xml' path='doc/member[@name="NV_GPU_CLIENT_ILLUM_ZONE_LOCATION.NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_INVALID"]/*' />
        NV_GPU_CLIENT_ILLUM_ZONE_LOCATION_INVALID = unchecked((int)(0xFFFFFFFF)),
    }
}
