namespace NVAPIWrapper
{
    /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER"]/*' />
    public enum NV_GPU_SCANOUT_COMPOSITION_PARAMETER
    {
        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_WARPING_RESAMPLING_METHOD"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_WARPING_RESAMPLING_METHOD = 0,

        /// <include file='NV_GPU_SCANOUT_COMPOSITION_PARAMETER.xml' path='doc/member[@name="NV_GPU_SCANOUT_COMPOSITION_PARAMETER.NV_GPU_SCANOUT_COMPOSITION_PARAMETER_SCANOUT_INTENSITY_METHOD"]/*' />
        NV_GPU_SCANOUT_COMPOSITION_PARAMETER_SCANOUT_INTENSITY_METHOD = 1,
    }
}
