namespace NVAPIWrapper
{
    /// <include file='NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.xml' path='doc/member[@name="NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE"]/*' />
    public enum NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE
    {
        /// <include file='NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.xml' path='doc/member[@name="NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.NV_GPU_CLOCK_FREQUENCIES_CURRENT_FREQ"]/*' />
        NV_GPU_CLOCK_FREQUENCIES_CURRENT_FREQ = 0,

        /// <include file='NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.xml' path='doc/member[@name="NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.NV_GPU_CLOCK_FREQUENCIES_BASE_CLOCK"]/*' />
        NV_GPU_CLOCK_FREQUENCIES_BASE_CLOCK = 1,

        /// <include file='NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.xml' path='doc/member[@name="NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.NV_GPU_CLOCK_FREQUENCIES_BOOST_CLOCK"]/*' />
        NV_GPU_CLOCK_FREQUENCIES_BOOST_CLOCK = 2,

        /// <include file='NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.xml' path='doc/member[@name="NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE.NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE_NUM"]/*' />
        NV_GPU_CLOCK_FREQUENCIES_CLOCK_TYPE_NUM = 3,
    }
}
