namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_USE_CODING_TYPE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_USE_CODING_TYPE = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_HEAAC"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_HEAAC,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_HEAACV2"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_HEAACV2,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_MPEGSURROUND"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_MPEGSURROUND,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE04"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE04,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE05"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE05,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE06"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE06,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE07"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE07,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE08"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE08,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE09"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE09,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE10"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE10,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE11"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE11,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE12"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE12,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE13"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE13,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE14"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE14,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE15"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE15,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE16"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE16,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE17"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE17,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE18"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE18,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE19"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE19,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE20"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE20,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE21"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE21,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE22"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE22,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE23"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE23,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE24"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE24,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE25"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE25,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE26"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE26,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE27"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE27,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE28"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE28,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE29"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE29,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE30"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE30,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE31"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_RESERVE31,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGEXTENSIONTYPE_AUTO = 63,
    }
}
