namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_PERMITTED"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_PERMITTED = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_PROHIBITED"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_PROHIBITED,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX.NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_DOWNMIX_AUTO = 3,
    }
}
