namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_IN_HEADER"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_IN_HEADER = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_2"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_2,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_4"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_4,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_5"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_5,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_6"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_6,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_7"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_7,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_8"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_8,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELCOUNT_AUTO = 15,
    }
}
