namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_NO_DATA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_NO_DATA = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_0DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_0DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_PLUS10DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_PLUS10DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_RESERVED03"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_RESERVED03,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL.NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LFEPLAYBACKLEVEL_AUTO = 7,
    }
}
