namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_NONE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_NONE = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X02"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X02,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X03"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X03,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X04"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X04,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X05"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X05,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X06"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X06,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X07"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X07,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X08"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X08,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X09"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X09,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X10"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_X10,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED10"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED10,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED11"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED11,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED12"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED12,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED13"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED13,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED14"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED14,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED15"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_RESERVED15,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION.NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_PIXELREPETITION_AUTO = 31,
    }
}
