namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_IN_HEADER"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_IN_HEADER = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_16BITS"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_16BITS,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_20BITS"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_20BITS,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_24BITS"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_24BITS,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLESIZE_AUTO = 7,
    }
}
