namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_IN_HEADER"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_IN_HEADER = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_32000HZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_32000HZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_44100HZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_44100HZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_48000HZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_48000HZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_88200KHZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_88200KHZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_96000KHZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_96000KHZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_176400KHZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_176400KHZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_192000KHZ"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_192000KHZ,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY.NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_SAMPLEFREQUENCY_AUTO = 15,
    }
}
