namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_NO_AFD"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_NO_AFD = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE01"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE01,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE02"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE02,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE03"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE03,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_LETTERBOX_GT16x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_LETTERBOX_GT16x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE05"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE05,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE06"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE06,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE07"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE07,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_EQUAL_CODEDFRAME"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_EQUAL_CODEDFRAME = 8,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_4x3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_4x3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_16x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_16x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_14x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_CENTER_14x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE12"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_RESERVE12,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_4x3_ON_14x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_4x3_ON_14x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_16x9_ON_14x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_16x9_ON_14x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_16x9_ON_4x3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_16x9_ON_4x3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOACTIVEPORTION_AUTO = 31,
    }
}
