namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_NO_DATA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_NO_DATA = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_HORIZONTAL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_HORIZONTAL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_VERTICAL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_VERTICAL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_BOTH"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_BOTH,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING.NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_NONUNIFORMPICTURESCALING_AUTO = 7,
    }
}
