namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_NODATA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_NODATA = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_OVERSCAN"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_OVERSCAN,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_UNDERSCAN"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_UNDERSCAN,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_FUTURE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_FUTURE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO.NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_SCANINFO_AUTO = 7,
    }
}
