namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_GRAPHICS"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_GRAPHICS = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_PHOTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_PHOTO,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_CINEMA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_CINEMA,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_GAME"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_GAME,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE.NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_CONTENTTYPE_AUTO = 7,
    }
}
