namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.NV_INFOFRAME_FIELD_VALUE_AVI_AFI_ABSENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_AFI_ABSENT = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.NV_INFOFRAME_FIELD_VALUE_AVI_AFI_PRESENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_AFI_PRESENT,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ACTIVEFORMATINFO.NV_INFOFRAME_FIELD_VALUE_AVI_AFI_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_AFI_AUTO = 3,
    }
}
