namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_DEFAULT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_DEFAULT = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_LIMITED_RANGE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_LIMITED_RANGE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_FULL_RANGE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_FULL_RANGE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_RESERVED"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_RESERVED,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_RGBQUANTIZATION_AUTO = 7,
    }
}
