namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_XVYCC601"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_XVYCC601 = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_XVYCC709"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_XVYCC709,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_SYCC601"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_SYCC601,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_ADOBEYCC601"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_ADOBEYCC601,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_ADOBERGB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_ADOBERGB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED05"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED05,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED06"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED06,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED07"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_RESERVED07,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_EXTENDEDCOLORIMETRY_AUTO = 15,
    }
}
