namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_NO_DATA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_NO_DATA = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_4x3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_4x3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_16x9"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_16x9,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_FUTURE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_FUTURE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME.NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ASPECTRATIOCODEDFRAME_AUTO = 7,
    }
}
