namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_0DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_0DB = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_1DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_1DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_2DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_2DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_3DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_3DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_4DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_4DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_5DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_5DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_6DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_6DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_7DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_7DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_8DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_8DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_9DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_9DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_10DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_10DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_11DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_11DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_12DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_12DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_13DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_13DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_14DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_14DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_15DB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_15DB,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES.NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_LEVELSHIFTVALUES_AUTO = 31,
    }
}
