namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_NO_DATA"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_NO_DATA = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_SMPTE_170M"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_SMPTE_170M,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_ITUR_BT709"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_ITUR_BT709,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_USE_EXTENDED_COLORIMETRY"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_USE_EXTENDED_COLORIMETRY,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY.NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORIMETRY_AUTO = 7,
    }
}
