namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_RGB"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_RGB = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_YCbCr422"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_YCbCr422,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_YCbCr444"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_YCbCr444,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_FUTURE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_FUTURE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT.NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_COLORFORMAT_AUTO = 7,
    }
}
