namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_IN_HEADER"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_IN_HEADER = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_PCM"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_PCM,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AC3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AC3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MPEG1"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MPEG1,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MP3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MP3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MPEG2"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MPEG2,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AACLC"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AACLC,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DTS"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DTS,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_ATRAC"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_ATRAC,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DSD"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DSD,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_EAC3"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_EAC3,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DTSHD"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DTSHD,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MLP"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_MLP,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DST"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_DST,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_WMAPRO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_WMAPRO,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_USE_CODING_EXTENSION_TYPE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_USE_CODING_EXTENSION_TYPE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE.NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CODINGTYPE_AUTO = 31,
    }
}
