namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_X_X_FR_FL = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_X_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_X_RC_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_X_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_RC_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_RRC_RLC_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_X_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_X_RC_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRC_FLC_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_FCH_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_FCH_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_FCH_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_X_FCH_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_X_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_X_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_X_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_X_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_X_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_X_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_X_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_X_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_RC_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_RC_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_RC_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_RC_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FCH_RC_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FCH_RC_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FCH_RC_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FCH_RC_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_FCH_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_FCH_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_FCH_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_TC_FCH_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRH_FLH_RR_RL_FC_LFE_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_FC_X_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_FC_X_FR_FL,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_FC_LFE_FR_FL"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_FRW_FLW_RR_RL_FC_LFE_FR_FL = 0X31,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION.NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AUDIO_CHANNELALLOCATION_AUTO = 0x1FF,
    }
}
