namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ITC.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ITC"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_ITC
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ITC.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ITC.NV_INFOFRAME_FIELD_VALUE_AVI_ITC_VIDEO_CONTENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ITC_VIDEO_CONTENT = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ITC.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ITC.NV_INFOFRAME_FIELD_VALUE_AVI_ITC_ITCONTENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ITC_ITCONTENT,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_ITC.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_ITC.NV_INFOFRAME_FIELD_VALUE_AVI_ITC_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_ITC_AUTO = 3,
    }
}
