namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_PROPERTY_BLACKLIST.xml' path='doc/member[@name="NV_INFOFRAME_PROPERTY_BLACKLIST"]/*' />
    public enum NV_INFOFRAME_PROPERTY_BLACKLIST
    {
        /// <include file='NV_INFOFRAME_PROPERTY_BLACKLIST.xml' path='doc/member[@name="NV_INFOFRAME_PROPERTY_BLACKLIST.NV_INFOFRAME_PROPERTY_BLACKLIST_FALSE"]/*' />
        NV_INFOFRAME_PROPERTY_BLACKLIST_FALSE = 0,

        /// <include file='NV_INFOFRAME_PROPERTY_BLACKLIST.xml' path='doc/member[@name="NV_INFOFRAME_PROPERTY_BLACKLIST.NV_INFOFRAME_PROPERTY_BLACKLIST_TRUE"]/*' />
        NV_INFOFRAME_PROPERTY_BLACKLIST_TRUE,
    }
}
