namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_LIMITED_RANGE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_LIMITED_RANGE = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_FULL_RANGE"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_FULL_RANGE,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_RESERVED02"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_RESERVED02,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_RESERVED03"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_RESERVED03,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION.NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_YCCQUANTIZATION_AUTO = 7,
    }
}
