namespace NVAPIWrapper
{
    /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA"]/*' />
    public enum NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA
    {
        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_NOT_PRESENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_NOT_PRESENT = 0,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_VERTICAL_PRESENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_VERTICAL_PRESENT,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_HORIZONTAL_PRESENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_HORIZONTAL_PRESENT,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_BOTH_PRESENT"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_BOTH_PRESENT,

        /// <include file='NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.xml' path='doc/member[@name="NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA.NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_AUTO"]/*' />
        NV_INFOFRAME_FIELD_VALUE_AVI_BARDATA_AUTO = 7,
    }
}
