namespace NVAPIWrapper
{
    /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK"]/*' />
    public enum NVAPI_GPU_WORKSTATION_FEATURE_MASK
    {
        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_SWAPGROUP"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_SWAPGROUP = 0x00000001,

        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_STEREO"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_STEREO = 0x00000010,

        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_WARPING"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_WARPING = 0x00000100,

        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_PIXINTENSITY"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_PIXINTENSITY = 0x00000200,

        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_GRAYSCALE"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_GRAYSCALE = 0x00000400,

        /// <include file='NVAPI_GPU_WORKSTATION_FEATURE_MASK.xml' path='doc/member[@name="NVAPI_GPU_WORKSTATION_FEATURE_MASK.NVAPI_GPU_WORKSTATION_FEATURE_MASK_BPC10"]/*' />
        NVAPI_GPU_WORKSTATION_FEATURE_MASK_BPC10 = 0x00001000,
    }
}
